name: Deploy Angular to OVH

on:
  push:
    branches:
      - master  # ou 'master' selon votre branche

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build:prod

    - name: Upload via FTP to OVH
      uses: eisberg-labs/ftp-deploy@v1.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/batuk/
        server-dir: ${{ secrets.FTP_TARGET_DIR }}
